/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.*;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minhduy
 */
public class panelSearch extends javax.swing.JPanel {

    /**
     * Creates new form panelSearch
     */
    DefaultListModel<String> model;
    IOFile file = new IOFile();
    JTextField mainTextField;
    Dictionary dict = new Dictionary();
    public panelSearch(JTextField textField) {
        initComponents();
        model = new DefaultListModel<String>();
        file.readFile("anhviet2.txt", dict);
        viewModel();
    }
    public  void viewModel(){
       for (Map.Entry<String, Word> entry : dict.getDict().entrySet()) {
            model.addElement(entry.getKey());
        }
        panelSearch.setModel(model); //
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelSearch = new javax.swing.JList<>();

        panelSearch.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelSearch.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                panelSearchValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(panelSearch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelSearchValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_panelSearchValueChanged
        String selectedWord =panelSearch.getSelectedValue();
        if(selectedWord!=null){
            mainTextField.setText(selectedWord);
           
        }
    }//GEN-LAST:event_panelSearchValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> panelSearch;
    // End of variables declaration//GEN-END:variables
}
